create hello world ACI test pipeline

diff --git a/.github/workflows/_cleanup.yml b/.github/workflows/_cleanup.yml
--- a/.github/workflows/_cleanup.yml
+++ b/.github/workflows/_cleanup.yml
@@ -4,16 +4,73 @@ on:
   workflow_call:
     inputs:
       cluster-name:
-        required: true
+        required: false
         description: AKS Cluster Name
         type: string
       skr-client-kid:
-        required: true
+        required: false
         description: SKR key id
         default: "default-skr-client-kid"
         type: string
+      debug:
+        description: "Debug Flag"
+        default: false
+        required: false
+        type: boolean
+  schedule:
+    - cron: "0 0 * * *"
 
 jobs:
+  cleanup-running-acis:
+    name: Cleanup Running Container Groups
+    runs-on: ubuntu-latest
+    if: ${{ inputs.debug == false || false }}
+    env: 
+      RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }} 
+    steps:
+      - name: Log into Azure
+        uses: azure/login@v2
+        with:
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+
+      - name: Delete All Container Groups
+        run: |
+          RUNNING_CONTAINERS=$(az container list \
+          --resource-group $RESOURCE_GROUP \
+          --query "[?!starts_with(name, 'uptime-')]")
+
+          for container in $(echo $RUNNING_CONTAINERS | jq -r '.[].id'); do
+              echo "Deleting container group: ${container}"
+              az resource delete --ids ${container}
+          done
+
+  cleanup-failed-acis:
+    name: Cleanup Failed Container Groups
+    runs-on: ubuntu-latest
+    if: ${{ inputs.debug == false || false }}
+    env: 
+      RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }} 
+    steps:
+      - name: Log into Azure
+        uses: azure/login@v2
+        with:
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+
+      - name: Delete Failed Container Groups
+        run: |
+          NON_RUNNING_CONTAINERS=$(az container list \
+          --resource-group $RESOURCE_GROUP \
+          --query "[?provisioningState=='Failed' || provisioningState=='Unhealthy']")
+
+          for container in $(echo $NON_RUNNING_CONTAINERS | jq -r '.[].id'); do
+          echo "Deleting container group: ${container}"
+          az resource delete --ids ${container}
+          done
+
   cleanup_registry:
     name: Cleanup Container Registry
     runs-on: ubuntu-latest
@@ -28,20 +85,27 @@ jobs:
       - name: Cleanup Public Azure Container Registry
         if: github.event_name != 'pull_request'
         run: |
+          # adding || true so that it doesn't fail if the image doesn't exist (i.e. either kafka or helloworld didn't run)
           az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}
-          az acr repository delete --name ${{ secrets.AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/kafka/consumer:${{ github.sha }} --yes
-          az acr repository delete --name ${{ secrets.AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/kafka/producer:${{ github.sha }} --yes
+          az acr repository delete --name ${{ secrets.AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/kafka/consumer:${{ github.sha }} --yes || true
+          az acr repository delete --name ${{ secrets.AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/kafka/producer:${{ github.sha }} --yes || true
+          az acr repository delete --name ${{ secrets.AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/aci/helloworld:${{ github.sha }} --yes || true
+          az acr repository delete --name ${{ secrets.AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/aks/helloworld:${{ github.sha }} --yes || true
 
       - name: Cleanup Test Azure Container Registry
         if: github.event_name == 'pull_request'
         run: |
+          # adding || true so that it doesn't fail if the image doesn't exist (i.e. either kafka or helloworld didn't run)
           az acr login --name ${{ secrets.TEST_AZURE_REGISTRY_NAME }}
-          az acr repository delete --name ${{ secrets.TEST_AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/kafka/consumer:${{ github.sha }} --yes
-          az acr repository delete --name ${{ secrets.TEST_AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/kafka/producer:${{ github.sha }} --yes
+          az acr repository delete --name ${{ secrets.TEST_AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/kafka/consumer:${{ github.sha }} --yes || true
+          az acr repository delete --name ${{ secrets.TEST_AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/kafka/producer:${{ github.sha }} --yes || true
+          az acr repository delete --name ${{ secrets.TEST_AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/aci/helloworld:${{ github.sha }} --yes || true
+          az acr repository delete --name ${{ secrets.TEST_AZURE_REGISTRY_NAME }} --image private/${{ github.actor }}/acc/samples/aks/helloworld:${{ github.sha }} --yes || true
 
   cleanup-cluster:
     name: Clean Up
     runs-on: ubuntu-latest
+    if: ${{ inputs.cluster-name != '' }}
     steps:
       - name: Log into Azure
         uses: azure/login@v2
