redo everything

diff --git a/.github/workflows/_cleanup.yml b/.github/workflows/_cleanup.yml
--- a/.github/workflows/_cleanup.yml
+++ b/.github/workflows/_cleanup.yml
@@ -1,9 +1,17 @@
-name: Cleanup
+name: Cleanup a Single AKS Cluster for a Pipeline Run
 
 on:
   workflow_call:
-  schedule:
-    - cron: "0 0 * * *"
+    inputs:
+      cluster-name:
+        required: true
+        description: AKS Cluster Name
+        type: string
+      skr-client-kid:
+        required: true
+        description: SKR key id
+        default: "default-skr-client-kid"
+        type: string
 
 jobs:
   cleanup_registry:
@@ -46,44 +54,45 @@ jobs:
         id: cleanup
         env: 
           RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
+          CLUSTER_NAME: ${{ inputs.cluster-name }}
+          SKR_CLIENT_KID: ${{ inputs.skr-client-kid }}
         run: | 
+          # cannot rely on the job success/fail indicator to determine whether the SKR_CLIENT_KID exists or not so attempt to delete anyway 
+          az keyvault key delete --vault-name kafka-test-pipeline-akv --name $SKR_CLIENT_KID 2>&1 || true
           result=$(az aks list -g $RESOURCE_GROUP --query "[].name" -o tsv)
 
-          for name in $result 
-          do
-              max_retries=5
-              retries=0
-              while [ $retries -lt $max_retries ]; do
-                  echo "Querying for cluster state"
-                  set -e
-                  EXIT_CODE=0
-                  clusterstate=$(az aks show -g $RESOURCE_GROUP -n $name --query 'provisioningState' -o tsv) || EXIT_CODE=$?
-                  if [[ $EXIT_CODE -eq 0 ]]; then
-                    # cluster still exists, try to delete
-                    if [[ $clusterstate == *"Succeeded"* ]]; then
-                        echo "Returned result is $clusterstate"
-                        echo "Cluster is ready to be deleted."
-                        powerState=$(az aks show -g $RESOURCE_GROUP -n $name --query "powerState.code" -o tsv)
-                        if [[ $powerState != *"Stopped"* ]]; then
-                          echo "Power state is $powerState, stopping"
-                          az aks stop --resource-group $RESOURCE_GROUP --name $name 2>&1
-                        fi
-                        az aks delete --resource-group $RESOURCE_GROUP --name $name --no-wait --yes
-                    elif [[ $clusterstate == *"Stopped"* ]] || [[ $clusterstate == *"Failed"* ]]; then
-                        echo "Returned result is $clusterstate"
-                        az aks delete --resource-group $RESOURCE_GROUP --name $name --no-wait --yes
-                    else
-                        echo "Returned cluster provisioning state is $clusterstate"
-                        echo "Retrying in 3 minutes..."
+          max_retries=5
+          retries=0
+          while [ $retries -lt $max_retries ]; do
+              echo "Querying for cluster state"
+              set -e
+              EXIT_CODE=0
+              clusterstate=$(az aks show -g $RESOURCE_GROUP -n $CLUSTER_NAME --query 'provisioningState' -o tsv) || EXIT_CODE=$?
+              if [[ $EXIT_CODE -eq 0 ]]; then
+                # cluster still exists, try to delete
+                if [[ $clusterstate == *"Succeeded"* ]]; then
+                    echo "Returned result is $clusterstate"
+                    echo "Cluster is ready to be deleted."
+                    powerState=$(az aks show -g $RESOURCE_GROUP -n $CLUSTER_NAME --query "powerState.code" -o tsv)
+                    if [[ $powerState != *"Stopped"* ]]; then
+                      echo "Power state is $powerState, stopping"
+                      az aks stop --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME 2>&1
                     fi
-                    retries=$((retries+1))
-                    sleep 180
-                  else
-                    break # Exit the loop since the cluster no longer exists
-                  fi
-              done
-              if [ $retries -eq $max_retries ]; then
-                  echo "The operation has been tried 5 times without success."
-                  exit 1
+                    az aks delete --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --no-wait --yes
+                elif [[ $clusterstate == *"Stopped"* ]] || [[ $clusterstate == *"Failed"* ]]; then
+                    echo "Returned result is $clusterstate"
+                    az aks delete --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --no-wait --yes
+                else
+                    echo "Returned cluster provisioning state is $clusterstate"
+                    echo "Retrying in 3 minutes..."
+                fi
+                retries=$((retries+1))
+                sleep 180
+              else
+                break # Exit the loop since the cluster no longer exists
               fi
           done
+          if [ $retries -eq $max_retries ]; then
+              echo "The operation has been tried 5 times without success."
+              exit 1
+          fi
